### PR TITLE
Problem: not using indent of 4 spaces (fix #253)

### LINKED ISSUE #253: Problem: not using indent of 4 spaces
indent with 4 spaces instread 2 spaces
```
find . -name "*.h" -o -name "*.cpp" -o -name "*.cc" -o -name "*.cs" | xargs clang-format -i -style="{SortIncludes: Never, IndentWidth: 4}"
```

### PR DESCRIPTION
**Pull request by leejw51crypto**
Solution: reformat with 4 spaces
```
find . -name "*.h" -o -name "*.cpp" -o -name "*.cc" -o -name "*.cs" | xargs clang-format -i -style="{SortIncludes: Never, IndentWidth: 4}"
```

### CODE REVIEW

**Review by tomtau — APPROVED** [review]
should this be specified in a `.clang-format` file and have a CI action to check new PRs against it: https://github.com/marketplace/actions/clang-format-check ?

**Comment by leejw51crypto** [comment]
ok, i'll check

**Review by elecming — APPROVED** [review]

**Comment by leejw51crypto** [comment]
resolving conflict

**Comment by leejw51crypto** [comment]
resolved, checking

**Pull request merged**
