### PR TITLE
Problem: Missing chain_id for wallet connect session (fix #257)

### LINKED ISSUE #257: Problem: Missing chain_id for wallet connect session
Chain id could be Number or Null according to spec when create a session.

### PR DESCRIPTION
**Pull request by elecming**
Close:
- #257

Solution:
- Add optional field chain_id for walletconnect (Empty String = None)

👮🏻👮🏻👮🏻 !!!! REFERENCE THE PROBLEM YOUR ARE SOLVING IN THE PR TITLE AND DESCRIBE YOUR SOLUTION HERE !!!! DO NOT FORGET !!!! 👮🏻👮🏻👮🏻

# PR Checklist:

- [ ] Have you read the [CONTRIBUTING.md](https://github.com/crypto-com/play-cpp-sdk/blob/main/CONTRIBUTING.md)?
- [ ] Does your PR follow the [C4 patch requirements](https://rfc.zeromq.org/spec:42/C4/#23-patch-requirements)?
- [ ] Have you rebased your work on top of the latest main? 
- [ ] Have you checked your code compiles? (`cargo build`)
- [ ] Have you included tests for any non-trivial functionality?
- [ ] Have you checked your code passes the unit tests? (`cargo test`)
- [ ] Have you checked your code formatting is correct? (`cargo fmt -- --check --color=auto`)
- [ ] Have you checked your basic code style is fine? (`cargo clippy`)
- [ ] If you added any dependencies, have you checked they do not contain any known vulnerabilities? (`cargo audit`)
- [ ] If your changes affect public APIs, does your PR follow the [C4 evolution of public contracts](https://rfc.zeromq.org/spec:42/C4/#26-evolution-of-public-contracts)?
- [ ] If your code changes public APIs, have you incremented the crate version numbers and documented your changes in the [CHANGELOG.md](https://github.com/crypto-com/play-cpp-sdk/blob/main/CHANGELOG.md)?
- [ ] If you are contributing for the first time, please read the agreement in [CONTRIBUTING.md](https://github.com/crypto-com/play-cpp-sdk/blob/main/CONTRIBUTING.md) now and add a comment to this pull request stating that your PR is in accordance with the [Developer's Certificate of Origin](https://github.com/crypto-com/play-cpp-sdk/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

Thank you for your code, it's appreciated! :)

### CODE REVIEW

**Comment by elecming** [comment]
See the tested demo: `default` Preferred Chain was set as Cronos Mainnet (chain id = 25).

**Review by tomtau — COMMENTED** [review]
why string and not u64?

**Comment by elecming** [comment]
@tomtau Rust side is Option<u64L>, String is for C++ (no optional value though...)

**Comment by tomtau** [comment]
why not to have u64 on the C++ side?

**Comment by tomtau** [comment]
if 0, it'll be None: https://chainlist.org

**Comment by elecming** [comment]
@tomtau Forced push and Changed String to u64.

**Review by tomtau — APPROVED** [review]

**Review by leejw51crypto — APPROVED** [review]
lgtm

**Pull request merged**
