### PR TITLE
Problem: changelog not update for v0.0.20-alpha (fix #441)

### LINKED ISSUE #441: Problem: changelog not update for v0.0.20-alpha
update changelog

### PR DESCRIPTION
**Pull request by leejw51crypto**
update changelog
update version

### CODE REVIEW

**Review by elecming — CHANGES_REQUESTED** [review]
Cargo.lock is not updated.

**Comment by leejw51crypto** [comment]
updated Cargo.lock

**Comment by leejw51crypto** [comment]
inspecting ci issues

**Comment by leejw51crypto** [comment]
close

**Pull request closed without merging**
