### PR TITLE
Problem: using namespace in c++ header (fix #81)

### LINKED ISSUE #81: Problem: using namespace in c++ header
this can cause compile issues in user side.

remove `using namespace rust;` in c++ header.
locate using namespace in c++ source only.

### PR DESCRIPTION
**Pull request by elecming**
Close:
- #81

Solution:
- Remove using namespace in headers/sources and keep it consistant

### CODE REVIEW

**Comment by elecming** [comment]
Seems rust `String` and c++'s `string` is very similar, it may confuse the users, so I removed all `using namespace` both headers and sources, except main.cc.

**Review by tomtau — COMMENTED** [review]
probably ok, but not sure why it was an issue in the first place: is it that those common symbol names (String, Vec, ...) may collide with other C++ definitions in other codebases (such as in UE), hence they need to be qualified with `rust::...`?

**Comment by elecming** [comment]
Probably it is the issue of using namespace in headers causes compilation failure in some cases? Including `using namespace` can not undo, it is dangerous to be used in headers (considering headers will be used anywhere). https://stackoverflow.com/questions/5849457/using-namespace-in-c-headers#:~:text=You%20should%20definitely%20NOT%20use,another%20reason%20it's%20so%20dangerous.

**Comment by tomtau** [comment]
ok, it's a common convention: https://stackoverflow.com/a/5849766

**Pull request merged**
