### PR TITLE
Problem: Missing examples of using the cpp sdk (fix #103)

### LINKED ISSUE #103: Problem: Missing examples of using the cpp sdk
We have a big demo, but not readable for users. 

Add examples, and keep them small, one file one example.

Another benefit is that small examples can be added into documents.
Also beneficial for unit tests.

### PR DESCRIPTION
**Pull request by elecming**
Solution:
- Add examples.

### CODE REVIEW

**Review by leejw51crypto — APPROVED** [review]
lgtm

**Comment by leejw51crypto** [comment]
how about replace auto with full name? for code readibility

**Comment by elecming** [comment]
ok, and I will add more examples and integrate them into documents as well.

**Comment by elecming** [comment]
Closed and will be done by **Fork and Pull** workflow in another PR

**Pull request closed without merging**
