### PR TITLE
Problem: defi-wallet-core not update (fix #371)

### LINKED ISSUE #371: Problem: defi-wallet-core not update
update to latest defi-wallet-core

### PR DESCRIPTION
**Pull request by leejw51crypto**
Solution: update defi-wallet-core

### CODE REVIEW

**Review by tomtau — COMMENTED** [review]
should we tag the version of defi-wallet-core or are we ok with just referring to the latest commit?

**Comment by leejw51crypto** [comment]
tagging seems better, i'll add release for defi-wallet-core-rs

**Comment by leejw51crypto** [comment]
working on integration ci errors

**Comment by leejw51crypto** [comment]
submit again

**Pull request closed without merging**
