### PR TITLE
Problem: Missing android build (fix #199)

### LINKED ISSUE #199: Problem: Missing android build

### PR DESCRIPTION
**Pull request by elecming**
Close:
- #199

Solution:
- Add android-build.yml
- Update Makefile to support armv7-linux-androideabi,
aarch64-linux-android, i686-linux-android, and x86_64-linux-android builds.

👮🏻👮🏻👮🏻 !!!! REFERENCE THE PROBLEM YOUR ARE SOLVING IN THE PR TITLE AND DESCRIBE YOUR SOLUTION HERE !!!! DO NOT FORGET !!!! 👮🏻👮🏻👮🏻

# PR Checklist:

- [ ] Have you read the [CONTRIBUTING.md](https://github.com/crypto-com/play-cpp-sdk/blob/main/CONTRIBUTING.md)?
- [ ] Does your PR follow the [C4 patch requirements](https://rfc.zeromq.org/spec:42/C4/#23-patch-requirements)?
- [ ] Have you rebased your work on top of the latest main? 
- [ ] Have you checked your code compiles? (`cargo build`)
- [ ] Have you included tests for any non-trivial functionality?
- [ ] Have you checked your code passes the unit tests? (`cargo test`)
- [ ] Have you checked your code formatting is correct? (`cargo fmt -- --check --color=auto`)
- [ ] Have you checked your basic code style is fine? (`cargo clippy`)
- [ ] If you added any dependencies, have you checked they do not contain any known vulnerabilities? (`cargo audit`)
- [ ] If your changes affect public APIs, does your PR follow the [C4 evolution of public contracts](https://rfc.zeromq.org/spec:42/C4/#26-evolution-of-public-contracts)?
- [ ] If your code changes public APIs, have you incremented the crate version numbers and documented your changes in the [CHANGELOG.md](https://github.com/crypto-com/play-cpp-sdk/blob/main/CHANGELOG.md)?
- [ ] If you are contributing for the first time, please read the agreement in [CONTRIBUTING.md](https://github.com/crypto-com/play-cpp-sdk/blob/main/CONTRIBUTING.md) now and add a comment to this pull request stating that your PR is in accordance with the [Developer's Certificate of Origin](https://github.com/crypto-com/play-cpp-sdk/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

Thank you for your code, it's appreciated! :)

### CODE REVIEW

**Comment by elecming** [comment]
For unreal 4.27.2,
```
UATHelper: Packaging (Android (ASTC)):   ERROR: Android toolchain NDK r25 not supported; please use NDK r21 to NDK r23 (NDK r21b recommended)
PackagingResults: Error: Android toolchain NDK r25 not supported; please use NDK r21 to NDK r23 (NDK r21b recommended)
```

**Comment by elecming** [comment]
To support both unreal 4 and 5 and future versions, two versions will be provided, 
- build with NDK r21e (tested on unreal 4.27, unreal 5 is to be tested)
- build with NDK r25b (the newest ndk version)

**Review by tomtau — APPROVED** [review]
do we need all the Android targets? wouldn't aarch64/armv7 be enough?

**Comment by elecming** [comment]
@tomtau Unreal 4 supports all four targets, but x86 seems are not supported in unreal 5.

**Review by leejw51crypto — APPROVED** [review]
lgtm

**Comment by tomtau** [comment]
@damoncro maybe we can remove the x86 targets, especially 32-bit x86 is pretty rare, because they are not common for Android devices? x86 is primarily useful if you want to test locally, but don't want to use an emulator

**Comment by elecming** [comment]
ok, good to remove in next release.

**Pull request merged**
